In [9]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd


In [17]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["Gender"]=le.fit_transform(data["Gender"])

data.head()


RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France       0   42   
1          2    15647311      Hill          608     Spain       0   41   
2          3    15619304      Onio          502    France       0   42   
3          4    15701354      Boni          699    France       0   39   
4          5    15737888  Mitchell          850     Spain       0   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [28]:
data.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France       0   42       2       0.00              1   
1          608     Spain       0   41       1   83807.86              1   
2          502    France       0   42       8  159660.80              3   
3          699    France       0   39       1       0.00              2   
4          850     Spain       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [32]:
data.Geography.unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [36]:
data["Geography"]=le.fit_transform(data["Geography"])
data.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [42]:
x= data.iloc[:,:-1]
y=data.iloc[:,-1]


In [45]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest= train_test_split(x,y,test_size=0.3, random_state=2)

In [47]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.transform(xtest)


In [70]:
from sklearn.linear_model import LogisticRegression
model_lr = LogisticRegression()
model_lr.fit(xtrain,ytrain)
yp=model_lr.predict(xtest[:])
yp.shape

(3000,)

In [72]:
from sklearn.metrics import confusion_matrix
confusion_matrix(ytest,yp)

array([[2332,   83],
       [ 491,   94]])

In [76]:
y.value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

## 

In [85]:
data2= pd.read_csv("Iris.csv")
data2.shape


(150, 6)

In [87]:
data2.head()


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [94]:


from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data2["Species"]=le.fit_transform(data2["Species"])
data2

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              5.1           3.5            1.4           0.2        0
1              4.9           3.0            1.4           0.2        0
2              4.7           3.2            1.3           0.2        0
3              4.6           3.1            1.5           0.2        0
4              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3        2
146            6.3           2.5            5.0           1.9        2
147            6.5           3.0            5.2           2.0        2
148            6.2           3.4            5.4           2.3        2
149            5.9           3.0            5.1           1.8        2

[150 rows x 5 columns]

In [96]:
x= data2.iloc[:,:-1]
y=data2.iloc[:,-1]


In [99]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest= train_test_split(x,y,test_size=0.3, random_state=2)

In [101]:
from sklearn.svm import SVC
model_svm=SVC()
model_svm.fit(xtrain,ytrain)

SVC()

In [103]:
yp=model_svm.predict(xtest)
yp

array([0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 2, 1,
       2, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1, 2, 1, 0, 2, 1, 1, 2, 1, 1, 2, 1,
       0])

In [105]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest,yp)

0.9777777777777777

In [108]:
y.value_counts()

0    50
1    50
2    50
Name: Species, dtype: int64

In [112]:
inp=[6.7 ,3.0 ,5.2 ,2.3 ]
inp=np.asarray(inp).reshape(1,-1)
model_svm.predict(inp)

/home/nmit/.local/lib/python3.10/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([2])